export interface Law {
  title: string;
  content: string;
}

export interface LawCategory {
  title: string;
  laws: Law[];
  footer: string;
}

export const lawsByCategory: Record<string, LawCategory> = {
  working: {
    title: "The 5 Laws of LLM-Assisted Working",
    laws: [
      {
        title: "1. Freedom of LLM Choice",
        content:
          "Professionals are free to select any large language model that best suits their specific tasks and goals. This flexibility enables customization, leverages diverse strengths of LLMs, and supports unique workflows across different fields of work.",
      },
      {
        title: "2. Task Context Comprehension and Validation",
        content:
          "All outputs generated by an LLM must be thoroughly understood and validated by the professional. Blindly adopting AI-generated suggestions without critical evaluation is prohibited. Professionals are responsible for ensuring the accuracy, relevance, and alignment of outputs with the specific context of their work.",
      },
      {
        title: "3. Human-AI Collaboration in Decision-Making",
        content:
          "The integration of LLMs must complement, not replace, human expertise. While LLMs can assist in generating ideas, solving problems, or streamlining workflows, the ultimate responsibility for decisions, refinements, and implementation lies with the human professional.",
      },
      {
        title: "4. Continuous Feedback and Adaptation",
        content:
          "Professionals must actively contribute to improving LLM-assisted workflows by providing feedback on the outputs, identifying areas for enhancement, and sharing best practices. This iterative approach ensures the effective and responsible use of LLMs across diverse applications.",
      },
      {
        title: "5. Ethical and Responsible Standards",
        content:
          "The use of LLMs in work must adhere to ethical principles and align with the values and standards of the field. Professionals must critically evaluate LLM outputs to avoid perpetuating biases, ensuring fairness, accountability, and compliance with industry norms and regulations.",
      },
    ],
    footer: "These laws establish a framework for integrating LLMs into professional workflows while maintaining high standards of quality, accountability, and ethical conduct. They promote the strategic use of AI as a collaborative tool while emphasizing the irreplaceable value of human expertise and judgment in the workplace.",
  },
  coding: {
    title: "The 5 Laws of LLM-Assisted Coding",
    laws: [
      {
        title: "1. Freedom of LLM Choice",
        content:
          "Developers are free to use any large language model of their choice for code generation. This allows for flexibility and leverages individual preferences and strengths of different LLMs.",
      },
      {
        title: "2. Comprehension Mandate",
        content:
          "All code generated with the assistance of an LLM must be thoroughly understood and validated by the developer (tester, architect, etc.). Developers are encouraged to document their understanding to ensure traceability and accountability. Simply copying and pasting without comprehension is strictly prohibited.",
      },
      {
        title: "3. Human-AI Collaboration in Review",
        content:
          "Final code review and publication must involve human oversight, complemented by automated tools for quality and security analysis. Reviewers may use LLMs to assist in the review process, but the ultimate decision and responsibility lie with the human reviewer.",
      },
      {
        title: "4. Continuous Learning and Improvement",
        content:
          "Developers and reviewers must actively contribute to improving the LLM-assisted coding process by providing feedback, identifying areas for improvement, and sharing best practices.",
      },
      {
        title: "5. Ethical and Secure Coding Standards",
        content:
          "All code, whether LLM-generated or not, must adhere to the organization's ethical guidelines and security standards. LLMs should be used to enhance, not compromise, code quality and security.",
      },
    ],
    footer: "These laws provide a framework for integrating LLMs into your coding workflow while maintaining high standards of code quality, security, and developer understanding. They encourage the use of AI as a powerful tool while emphasizing the critical role of human expertise and oversight in the software development process.",
  },
  design: {
    title: "The 5 Laws of LLM-Assisted Design",
    laws: [
      {
        title: "1. Freedom of LLM Choice",
        content:
          "Designers are free to choose any large language model suited to their creative process. This flexibility allows leveraging the unique strengths of different LLMs, fostering innovation, and adapting to the diverse needs of design challenges.",
      },
      {
        title: "2. Design Context Comprehension",
        content:
          "All design concepts or outputs generated with LLM assistance must be thoroughly understood and contextualized by the designer. Designers must validate and adapt these outputs to ensure relevance, creativity, and alignment with project goals. Blindly adopting generated outputs without understanding their implications is strictly prohibited.",
      },
      {
        title: "3. Human-AI Collaboration in Refinement",
        content:
          "The refinement of design outputs must involve human oversight, blending AI-generated ideas with the designer's expertise and creativity. While LLMs can propose innovative concepts, the ultimate design decisions, adjustments, and artistic coherence rest with the human designer.",
      },
      {
        title: "4. Iterative Learning and Process Enhancement",
        content:
          "Designers and teams must continuously evaluate and refine their workflows involving LLMs. Feedback loops, case studies, and sharing best practices should drive the improvement of how LLMs are integrated into the design process, ensuring their effective and responsible use.",
      },
      {
        title: "5. Ethical and Inclusive Design Standards",
        content:
          "LLM-assisted designs must adhere to ethical principles and promote inclusivity. Designers must critically evaluate outputs to avoid perpetuating biases or stereotypes and ensure that designs generated with LLM assistance align with accessibility and sustainability goals.",
      },
    ],
    footer: "These laws establish guidelines for incorporating LLMs into the creative design process while upholding principles of artistic integrity, user-centered design, and ethical considerations. They promote AI as an innovative design partner while preserving the essential human elements of creativity, empathy, and design thinking.",
  },
  teaching: {
    title: "The 5 Laws of LLM-Assisted Teaching",
    laws: [
      {
        title: "1. Freedom of LLM Choice",
        content:
          "Educators are free to select any large language model that aligns with their teaching objectives and audience needs. This flexibility enables customization and adapts to various educational contexts, enhancing the learning experience.",
      },
      {
        title: "2. Pedagogical Alignment and Validation",
        content:
          "All content or lesson plans generated by an LLM must be critically reviewed and aligned with the educator's pedagogical goals. Teachers must ensure that the material is accurate, contextually relevant, and supportive of desired learning outcomes, avoiding uncritical adoption of AI-generated content.",
      },
      {
        title: "3. Human-AI Collaboration in Learning Facilitation",
        content:
          "Teaching processes must involve active collaboration between educators and LLMs. While LLMs can assist by generating content, answering questions, or facilitating discussions, the educator remains responsible for guiding the learning process, contextualizing information, and fostering critical thinking.",
      },
      {
        title: "4. Iterative Feedback and Improvement",
        content:
          "Educators must continuously assess the effectiveness of LLMs in supporting teaching and learning. Regular feedback from students and iterative improvements in how LLMs are integrated into lessons help refine their role in the educational process.",
      },
      {
        title: "5. Ethical and Inclusive Educational Standards",
        content:
          "LLM-assisted teaching must adhere to ethical guidelines, promoting inclusivity, accessibility, and fairness. Educators must ensure that AI-generated materials do not perpetuate biases and that the teaching environment remains respectful, equitable, and supportive of diverse learners.",
      },
    ],
    footer: "These laws create a foundation for integrating LLMs into educational practices while maintaining pedagogical excellence, student engagement, and learning outcomes. They position AI as a valuable educational tool while emphasizing the irreplaceable role of human educators in nurturing critical thinking and personal development.",
  },
  medicine: {
    title: "The 5 Laws of LLM-Assisted Medicine",
    laws: [
      {
        title: "1. Freedom of LLM Choice",
        content:
          "Healthcare professionals can select the most appropriate large language model tailored to their medical specialty and task requirements. This flexibility ensures LLMs support diverse applications, from patient education to clinical decision support.",
      },
      {
        title: "2. Clinical Context Comprehension and Validation",
        content:
          "All recommendations or insights generated by an LLM must be thoroughly validated by the healthcare professional. Blind reliance on AI outputs is prohibited. Physicians and clinicians remain responsible for ensuring the medical relevance, accuracy, and safety of all LLM-assisted contributions.",
      },
      {
        title: "3. Human-AI Collaboration in Patient Care",
        content:
          "LLMs are tools to support, not replace, the expertise of medical professionals. While LLMs can assist in synthesizing patient data, suggesting diagnoses, or streamlining administrative tasks, the ultimate responsibility for patient care and decision-making lies solely with the healthcare professional.",
      },
      {
        title: "4. Iterative Feedback and Continuous Improvement",
        content:
          "Healthcare professionals must evaluate the performance of LLMs regularly, providing feedback on their accuracy, relevance, and usability. Lessons learned should be used to refine how LLMs are integrated into medical workflows, enhancing their effectiveness over time.",
      },
      {
        title: "5. Ethical and Patient-Centric Standards",
        content:
          "The use of LLMs in medicine must uphold the highest ethical standards, prioritizing patient safety, privacy, and dignity. Healthcare professionals must critically review LLM outputs to prevent perpetuating biases and ensure that care remains equitable, transparent, and aligned with regulatory standards.",
      },
    ],
    footer: "These laws establish crucial guidelines for incorporating LLMs into healthcare practices while maintaining the highest standards of patient care, medical ethics, and professional responsibility. They frame AI as a powerful clinical support tool while affirming the paramount importance of human medical expertise and the doctor-patient relationship.",
  },
  justice: {
    title: "The 5 Laws of LLM-Assisted Justice",
    laws: [
      {
        title: "1. Freedom of LLM Choice",
        content:
          "Legal professionals can choose the most appropriate large language model based on their area of expertise and case requirements. This flexibility ensures LLMs can support diverse legal applications, from case research to drafting legal documents.",
      },
      {
        title: "2. Legal Context Comprehension and Validation",
        content:
          "All outputs generated by an LLM, such as legal arguments, interpretations, or document drafts, must be critically reviewed and validated by the legal professional. Blind reliance on LLM outputs is prohibited. Lawyers and judges are responsible for ensuring that the content aligns with applicable laws and judicial principles.",
      },
      {
        title: "3. Human-AI Collaboration in Legal Processes",
        content:
          "LLMs are tools to enhance, not replace, human judgment in the justice system. While LLMs can assist with research, analysis, and document preparation, the final responsibility for decisions and arguments remains with the legal professional or judicial authority.",
      },
      {
        title: "4. Iterative Feedback and Continuous Improvement",
        content:
          "Legal professionals must provide feedback on LLM outputs to identify inaccuracies, biases, or gaps. This iterative process ensures LLMs are continuously refined to improve their effectiveness and reliability within the legal context.",
      },
      {
        title: "5. Ethical and Justice-Oriented Standards",
        content:
          "The use of LLMs in legal practice must adhere to the highest ethical standards, ensuring fairness, impartiality, and confidentiality. Legal professionals must critically assess LLM outputs to avoid perpetuating biases and ensure they contribute to equitable access to justice and compliance with legal norms.",
      },
    ],
    footer: "These laws provide a framework for integrating LLMs into legal practice while upholding the principles of justice, due process, and professional ethics. They position AI as a valuable legal resource while emphasizing the essential role of human judgment, legal expertise, and ethical considerations in the administration of justice.",
  },
}; 